kind: ConfigMap
apiVersion: v1
metadata:
  name: identity-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: identity
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  PATH_BASE: /identity
  SeqServerUrl: http://seq
{{- if .Values.enableIngress }}
  BlazorClientUrlExternal: http://{{ .Values.externalDnsNameOrIP}}
{{- else }}
  BlazorClientUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30000
  BasketApiUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30005
  OrderingApiUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30002
  ShoppingAggregatorApiUrlExternal: http://{{ .Values.externalDnsNameOrIP}}:30006
{{- end }}
  # Temporarily while waiting for https://github.com/dapr/dotnet-sdk/issues/779 to get fixed.
  ConnectionStrings__IdentityDB: Server=sqldata;Database=Microsoft.eShopOnDapr.Service.IdentityDb;User Id=sa;Password=Pass@word;TrustServerCertificate=true

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: identity
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      service: identity
  template:
    metadata:
      labels:
        app: eshop
        service: identity
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "identity-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        dapr.io/log-as-json: "true"
    spec:
      containers:
        - name: identity-api
          image: eshopdapr/identity.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: identity-cm
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

---

kind: Service
apiVersion: v1
metadata:
  name: identity-api
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: identity
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
      protocol: TCP
      name: http
  selector:
    service: identity

{{- if .Values.enableIngress }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-api-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: identity
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths: 
      - path: /identity(/.*)
        pathType: Prefix
        backend:
          service:
            name: identity-api
            port: 
              number: 80
{{- end }}