kind: Deployment
apiVersion: apps/v1
metadata:
  name: seq
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: seq
spec:
  replicas: 1
  selector:
    matchLabels:
      service: seq
  template:
    metadata:
      labels:
        app: eshop
        service: seq
    spec:
      containers:
      - name: seq
        image: datalust/seq:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: BASE_URI
            value: /seq
          - name: SEQ_API_CANONICALURI
            value: /seq

---

kind: Service
apiVersion: v1
metadata:
  name: seq
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: seq
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
      protocol: TCP
      name: http
  selector:
    service: seq
{{- if .Values.enableIngress }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seq-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: eshop
    service: seq
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths: 
      - path: /seq
        pathType: Prefix
        backend:
          service:
            name: seq
            port: 
              number: 80
{{- end }}